### PR TITLE
feat: update charts index format

### PR DESCRIPTION
**Pull request by tompizmor**
Update charts-index format and default name of the index

### CODE REVIEW

**Comment by tompizmor** [comment]
Not sure if we should make `useChartsIndex` config property true by default so no special configuration is needed for VAC repositories

**Review by jotadrilo — APPROVED** [review]
LGTM!

However, I think this PR deserves a better description and background. Please state that we would like to use a charts-specific index that contains all chart versions released internally, unequivocally.

**Review by migmartri — APPROVED** [review]
LGTM!

**Comment by migmartri** [comment]
> Not sure if we should make useChartsIndex config property true by default so no special configuration is needed for VAC repositories

Yeah, same thing about relocateContainerImages. if we want to make this tool to work ootbox with TAC repositories those two option defaults should be set.

Maybe we can do it in another PR and document the reasoning wdyt?

**Review by migmartri — APPROVED** [review]

**Pull request merged**
